"use client"
import { useEffect } from "react";
import { useRouter } from "next/navigation";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import Login from "./(auth)/login/page";
import Mainbody from "./components/Mainbody";
import LocationInput from "./components/Location_input";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Next RedBus App",
//   description: "Generated by Mahiboob",
// };

export default function RootLayout({ children,Login }) {
  const router = useRouter();

    useEffect(() => {
        const userId = window.localStorage.getItem('id');
        if (!userId) {
            router.push('/login');
        }
    }, [router]);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {Login}
        <Header />
        {children}
      </body>
    </html>
  );
}
